sudo: false
language: python
python:
  - "3.6"
install: pip install tox-travis
script: tox
branches:
  only:
    - master
    - release
deploy:
  skip_cleanup: true
  provider: pypi
  user: $PYPI_USER
  password: $PYPI_PASS
  distributions: bdist_wheel
  on:
    branch: release
