sudo: false
language: python
python:
  - "3.6"
install: pip install tox-travis
script: tox
branches:
  only:
    - master
    - release
deploy:
  skip_cleanup: true
  provider: pypi
  user: trojkat
  password:
    secure: CxilApVEq7/QuXLWlIj5s6BJ7wWnfiesiwgTFTGAEqlxZHCDb+/xmRhWIOC2XHOkGYalbZ9yRJsHLVGuSv+voiMcDMgGBcwVB1e0WPGAcvm1efvwFdD3XR0HbIftJV/5E+BawPB2QbjOsi5WnbU9GHzHanOuXBdzSUGa3tFFgjlgEWS55TXN9a110nqVf+PQGwjrkd8MPLyCVzP3+Nn14dbaiORTaaQEGLdVs7TDu7RRi5gEIA8SYYR5ZDuDr55V96fTpcVIy2c/MhigxuVxMcgKVGylGq3gWBSZPLL/iAiaKaCQtiruJUtZp7kvsIL/aTviuLk9LhQdHLatW+hrtj4w9Nxs0cFcbeOjIa9Hna4+zL4fNDzF7aCRLGl9P45y/8Gy5hAKao+fbGEptqclb0JwBt2ZkmojCk/6Hkb2Z25jzjASeGmNl5ui/L25zqeLq8OswOetnxOQhNBv2PYFpj/pMYoI5bGNNivwpvNCmM+pV7eW5MgF9rF9YkOXFdKh9viz9OypHeFie0vlO/LNrDtyw+f7V594RCvBFw4qJM9Xh+Xy1E3qw0w66fuN3x+CHNYyWEYlZnRUDM47Zap7dR/T6HmoZDeIXG929+ewsMf1/GtguOdjxKTIYa5rbkWSXGWfJjKxuhvmINZsm9FncfvUTisqu8WJoq+qVN6n8fo=
  distributions: bdist_wheel
  on:
    branch: release
